builds:
  - binary: envkey-source
    ldflags:
      - '-s -w'
      - '-extldflags "-static" -X github.com/org2321/reponame/public/sdks/envkey-source/version.Version={{.Env.ENVKEYSOURCE_VERSION}}'
    env:
      - CGO_ENABLED=0
      - GOROOT_FINAL=/usr/go
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

